---
title: "Validate Metadata"
author: "Kaelyn Long"
date: "`r format(Sys.time(), '%B %d, %Y')`"
format:
    html:
        fontsize: 14pxs
        toc: true
        top-depth: 3
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(curatedMetagenomicDataCuration)
```

```{r}
## Run test validation
# Import cMD data dictionary
dictpath <- system.file("extdata", "cMD_data_dictionary.csv",
                        package = "curatedMetagenomicDataCuration")

cdd <- read.csv(dictpath,
                colClasses = "character")

# Load in test studies
curpath <- system.file("curated", package = "curatedMetagenomicDataCuration")
as_names <- list.files(curpath, pattern = "_metadata.tsv",
                       recursive = TRUE, full.names = TRUE)
ts <- as[[1]]

# Two options for validating a single study
report <- dplyr::bind_rows(
  check_required(cdd, ts),
  check_class(cdd, ts),
  check_unique(cdd, ts),
  check_allowed_values(cdd, ts)
)

full_report <- dplyr::bind_rows(
  check_required(cdd, ts, include_all = TRUE),
  check_class(cdd, ts, include_all = TRUE),
  check_unique(cdd, ts, include_all = TRUE),
  check_allowed_values(cdd, ts, include_all = TRUE)
)

# Run validation on all studies
check_all <- lapply(as, function(x) {
  print(unique(x$study_name))
  report <- dplyr::bind_rows(
    check_required(cdd, x),
    check_class(cdd, x),
    check_unique(cdd, x),
    check_allowed_values(cdd, x)
  )
})
```

