#' @title CURIE Pattern for Derived Ontology Term ID Columns
#' @description Regex (unanchored, matching the convention already used by
#'   other \code{corpus.type == "regexp"} dictionary rows, e.g. \code{age_max})
#'   for a well-formed ontology CURIE such as \code{NCIT:C142703} or
#'   \code{UBERON:0001988}. Namespace-agnostic by design: it accepts any
#'   ontology prefix already used in this project's dictionary, and rejects
#'   the underscore form (\code{NCIT_C142703}) reported in issue #162.
#' @keywords internal
#' @noRd
ONTOLOGY_TERM_ID_PATTERN <- "[A-Za-z]+:[A-Za-z0-9]+"

#' @title Add Ontology Term ID Rows to the Data Dictionary
#' @description \code{table_to_yaml_schema()} only emits a schema entry for
#'   columns that are literal rows in the data dictionary. The
#'   \code{<field>_ontology_term_id} companion columns that
#'   \code{add_ontology_columns()} derives from every ontology-backed field
#'   (one with a \code{static.enum} or \code{dynamic.enum} mapping) have no
#'   such row, so they were never validated and malformed CURIEs like
#'   \code{NCIT_C142703} went undetected (issue #162). This synthesizes one
#'   \code{corpus.type = "regexp"} row per ontology-backed field, mirroring
#'   its \code{multiplevalues}/\code{delimiter}, so the existing regexp
#'   validation path picks it up like any other field.
#' @param dict Data dictionary data.frame (as read from
#'   \code{cMD_data_dictionary.csv}).
#' @return \code{dict} with the synthesized rows appended.
#' @keywords internal
#' @noRd
.add_ontology_id_schema_rows <- function(dict) {
  is_ontology_backed <- (!is.na(dict$static.enum) & nzchar(dict$static.enum)) |
    (!is.na(dict$dynamic.enum) & nzchar(dict$dynamic.enum))
  fields <- dict$col.name[is_ontology_backed]
  oid_cols <- paste0(fields, "_ontology_term_id")
  fields <- fields[!oid_cols %in% dict$col.name]
  if (length(fields) == 0) return(dict)

  src <- dict[match(fields, dict$col.name), , drop = FALSE]
  new_rows <- dict[rep(NA_integer_, length(fields)), , drop = FALSE]
  rownames(new_rows) <- NULL
  new_rows$col.name <- paste0(fields, "_ontology_term_id")
  new_rows$col.class <- "character"
  new_rows$unique <- "non-unique"
  new_rows$required <- "optional"
  new_rows$multiplevalues <- src$multiplevalues
  new_rows$description <- paste0("Ontology term ID(s) for '", fields,
                                  "', derived by add_ontology_columns().")
  new_rows$allowedvalues <- ONTOLOGY_TERM_ID_PATTERN
  new_rows$delimiter <- src$delimiter
  new_rows$corpus.type <- "regexp"

  rbind(dict, new_rows)
}

#' @title Load Validation Schema
#' @description Load a \code{*_data_dictionary.csv} from a package's
#'   \code{inst/extdata} and convert it to a validation schema via
#'   \code{\link[OmicsMLRepoCuration]{table_to_yaml_schema}}. Derived
#'   \code{*_ontology_term_id} columns are given a CURIE validation pattern
#'   before conversion.
#' @param package Package whose \code{inst/extdata} contains the data
#'   dictionary CSV.
#' @return List containing the loaded schema
#' @export
load_validation_schema <- function(package = "curatedMetagenomicDataCuration") {
  dict_file <- ""
  # First try local dev tree (inst/extdata/)
  local_dir <- file.path("inst", "extdata")
  if (dir.exists(local_dir)) {
    hits <- list.files(local_dir, pattern = "_data_dictionary\\.csv$",
                       full.names = TRUE)
    if (length(hits) > 0) dict_file <- hits[1]
  }
  # Fallback to the installed package
  if (!nzchar(dict_file) || !file.exists(dict_file)) {
    pkg_dir <- system.file("extdata", package = package)
    hits <- list.files(pkg_dir, pattern = "_data_dictionary\\.csv$",
                       full.names = TRUE)
    if (length(hits) == 0)
      stop("No *_data_dictionary.csv found in package '", package, "'")
    dict_file <- hits[1]
  }
  schema_table <- read.csv(dict_file, stringsAsFactors = FALSE)
  # Guard against a mis-delimited dictionary (e.g. space- instead of
  # comma-separated). read.csv silently collapses such a file into a single
  # column, which later crashes table_to_yaml_schema with an opaque
  # "$ operator is invalid for atomic vectors". Fail early with a clear message.
  if (ncol(schema_table) < 2 || !"col.name" %in% names(schema_table)) {
    stop("Data dictionary '", dict_file, "' parsed into ",
         ncol(schema_table), " column(s) without a 'col.name' column. ",
         "The file is likely not comma-delimited — check its field separator.")
  }
  schema_table <- .add_ontology_id_schema_rows(schema_table)
  OmicsMLRepoCuration::table_to_yaml_schema(schema_table)
}

#' @title Load Ontology Terms
#' @description Load this project's precomputed ontology terms artifact
#'   (\code{inst/extdata/cmd_ontology_terms.rds}) used to validate ontology-backed
#'   (dynamic_enum) fields offline. The artifact is project-specific and lives in
#'   this project; it is generated by \code{inst/scripts/make_ontology_terms.R}
#'   and passed to \code{\link[OmicsMLRepoCuration]{validate_data_against_schema}}.
#' @param package Package whose \code{inst/extdata} contains the artifact.
#' @return A named list keyed by field name (each with \code{labels} and
#'   \code{synonym_lookup}), or an empty list if the artifact is absent.
#' @export
load_ontology_terms <- function(package = "curatedMetagenomicDataCuration") {
  rds_file <- ""
  # First try local dev tree (inst/extdata/)
  local_file <- file.path("inst", "extdata", "cmd_ontology_terms.rds")
  if (file.exists(local_file)) {
    rds_file <- local_file
  } else {
    # Fallback to the installed package
    pkg_file <- system.file("extdata", "cmd_ontology_terms.rds", package = package)
    if (nzchar(pkg_file) && file.exists(pkg_file)) rds_file <- pkg_file
  }
  if (!nzchar(rds_file)) return(list())
  terms <- readRDS(rds_file)
  if (!is.list(terms)) return(list())
  terms
}

#' @title Find Metadata Files
#' @description Find all *_sample.tsv files in curated directory
#' @param path Base path to search (default: "inst/curated/")
#' @return Character vector of file paths
#' @export
find_metadata_files <- function(path = "inst/curated/") {
  list.files(path, pattern = "_sample\\.tsv$",
             full.names = TRUE, recursive = TRUE)
}

#' @title Uncurated Column Prefix
#' @description Columns carrying original, study-specific metadata are kept
#'   alongside the curated fields under this prefix. They are preserved as-is
#'   and are deliberately exempt from schema validation.
#' @keywords internal
#' @noRd
UNCURATED_PREFIX <- "uncurated_"

#' @title Identify Uncurated Columns
#' @description Return the names of columns that use the \code{uncurated_}
#'   prefix and are therefore outside the validated schema.
#' @param data A data.frame of curated metadata
#' @return Character vector of column names (possibly empty)
#' @examples
#' d <- data.frame(age = 1L, uncurated_DAS28 = 3.1, check.names = FALSE)
#' uncurated_columns(d)
#' @export
uncurated_columns <- function(data) {
  names(data)[startsWith(names(data), UNCURATED_PREFIX)]
}

#' @title Validate Single Study
#' @description Validate a single metadata file against schema.
#'   Columns prefixed with \code{uncurated_} preserve original study fields
#'   that have no counterpart in the data dictionary. They are withheld from
#'   the schema check rather than reported as uncovered columns, and are
#'   counted in the returned \code{n_uncurated}.
#' @param file Path to TSV file
#' @param schema Validation schema object
#' @param ontology_terms Named list of precomputed ontology terms (from
#'   \code{\link{load_ontology_terms}}) used to validate dynamic_enum fields.
#'   Default \code{NULL} skips ontology-backed value checks.
#' @return List with validation results and metadata
#' @export
validate_single_study <- function(file, schema, ontology_terms = NULL) {
  study_name <- basename(dirname(file))

  tryCatch({
    first_line <- readLines(file, n = 1L)
    sep <- if (grepl("\t", first_line)) "\t" else ","
    data <- read.delim(file, sep = sep, stringsAsFactors = FALSE,
                       check.names = FALSE)

    # Withhold uncurated_* columns from the schema check; they are retained in
    # `data` so downstream statistics and reports see the file as curated.
    uncurated <- uncurated_columns(data)
    curated_data <- data[, setdiff(names(data), uncurated), drop = FALSE]

    result <- OmicsMLRepoCuration::validate_data_against_schema(
      curated_data, schema, ontology_terms = ontology_terms)

    list(
      study_name = study_name,
      file = file,
      rows = nrow(data),
      cols = ncol(data),
      n_uncurated = length(uncurated),
      data = data,
      errors = result$errors,
      warnings = result$warnings,
      success = TRUE
    )
  }, error = function(e) {
    list(
      study_name = study_name,
      file = file,
      rows = NA,
      cols = NA,
      n_uncurated = NA_integer_,
      data = NULL,
      errors = paste("VALIDATION ERROR:", conditionMessage(e)),
      warnings = character(0),
      success = FALSE
    )
  })
}

#' Validate a single study's curated metadata
#'
#' A user-friendly wrapper around the internal validation pipeline.
#' Accepts a study name (e.g. \code{"LeeKA_2022"}) or a direct path to a
#' \code{*_sample.tsv} file, loads the schema automatically, and prints a
#' readable summary to the console.
#'
#' @param study A study name (e.g. \code{"LeeKA_2022"}) to look up in the
#'   package's \code{inst/curated/} directory, or a full path to a
#'   \code{*_sample.tsv} file.
#' @param verbose Logical. If \code{TRUE} (default), print errors and warnings
#'   in full after the summary header.
#'
#' @return Invisibly returns a list with components:
#'   \describe{
#'     \item{study_name}{Study identifier derived from the directory name.}
#'     \item{file}{Resolved path to the TSV file.}
#'     \item{rows}{Number of samples (rows) in the file.}
#'     \item{cols}{Number of columns in the file.}
#'     \item{errors}{Character vector of validation errors (empty if none).}
#'     \item{warnings}{Character vector of validation warnings (empty if none).}
#'     \item{passed}{Logical; \code{TRUE} when there are no errors.}
#'   }
#'
#' @examples
#' \dontrun{
#' # By study name (looks up inst/curated/LeeKA_2022/LeeKA_2022_sample.tsv)
#' validateStudy("LeeKA_2022")
#'
#' # By explicit file path
#' validateStudy("path/to/MyStudy_2024_sample.tsv")
#' }
#'
#' @export
validateStudy <- function(study, verbose = TRUE) {
  # ── Resolve file path ────────────────────────────────────────────────────────
  if (file.exists(study)) {
    file <- study
  } else {
    # Treat `study` as a study name; look it up in inst/curated/
    curated_dir <- system.file("curated", package = "curatedMetagenomicDataCuration")
    if (!nzchar(curated_dir)) {
      # Fall back to working-directory layout (development use)
      curated_dir <- file.path("inst", "curated")
    }
    file <- file.path(curated_dir, study, paste0(study, "_sample.tsv"))
    if (!file.exists(file)) {
      stop(
        "Could not find metadata file for study '", study, "'.\n",
        "  Looked at: ", file, "\n",
        "  Pass a full file path or check that the study name is correct."
      )
    }
  }

  # ── Load schema & validate ───────────────────────────────────────────────────
  schema         <- load_validation_schema()
  ontology_terms <- load_ontology_terms()
  res            <- validate_single_study(file, schema, ontology_terms)

  n_errors   <- length(res$errors)
  n_warnings <- length(res$warnings)
  passed     <- res$success && n_errors == 0L

  # ── Print summary ────────────────────────────────────────────────────────────
  status_icon <- if (passed) "[PASS]" else "[FAIL]"
  cat(rep("-", 60), "\n", sep = "")
  cat(status_icon, res$study_name, "\n")
  if (!is.na(res$rows))
    cat("  File   :", res$file, "\n",
        " Samples :", res$rows, "rows x", res$cols, "columns\n")

  if (!res$success) {
    cat("  ERROR  : could not read file\n")
  } else if (passed && n_warnings == 0L) {
    cat("  Result : no errors or warnings\n")
  } else {
    if (n_errors > 0L)
      cat("  Errors  :", n_errors, "\n")
    if (n_warnings > 0L)
      cat("  Warnings:", n_warnings, "\n")
  }
  cat(rep("-", 60), "\n", sep = "")

  if (verbose) {
    if (n_errors > 0L) {
      cat("Errors:\n")
      for (e in res$errors) cat("  ERROR:", e, "\n")
    }
    if (n_warnings > 0L) {
      cat("Warnings:\n")
      for (w in res$warnings) cat("  WARN :", w, "\n")
    }
  }

  invisible(list(
    study_name = res$study_name,
    file       = res$file,
    rows       = res$rows,
    cols       = res$cols,
    errors     = res$errors,
    warnings   = res$warnings,
    passed     = passed
  ))
}

#' @title Aggregate Validation Results
#' @description Combine validation results from all studies
#' @param results List of validation results
#' @return List with aggregated statistics
#' @export
aggregate_validation_results <- function(results) {
  total_errors <- sum(sapply(results, function(r) length(r$errors)))
  total_warnings <- sum(sapply(results, function(r) length(r$warnings)))
  all_valid <- all(sapply(results, function(r) length(r$errors) == 0))

  studies_with_issues <- results[sapply(results, function(r)
    length(r$errors) > 0 || length(r$warnings) > 0)]

  list(
    total_files = length(results),
    total_errors = total_errors,
    total_warnings = total_warnings,
    files_with_issues = length(studies_with_issues),
    all_valid = all_valid,
    status = ifelse(all_valid, "PASS", "FAIL"),
    studies_with_issues = studies_with_issues
  )
}
